openapi: 3.0.3
info:
  title: SALI DRAFT API Standards v0.2
  description: |-
    SALI is a not-for-profit organization comprised of legal industry professionals from legal operations, law firms and solution providers with the goal of developing open, practical industry standards for efficient and innovative legal services. _You can find more information at: [https://www.sali.org](https://www.sali.org)._

    This document contains a set of API Standrads compliant with SALI and the [Legal Matter Specification Standard](https://www.sali.org/Using-the-LMSS).

  license:
    name: SALI Open Standard Policy
    url: https://www.sali.org/Frequently-Asked-Questions
  version: 1.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/SALI-LMSS-V1/LMSS-API/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://app.swaggerhub.com/apis/SALI-LMSS-V1/LMSS-API/1.0.0
tags:
  - name: supported
    description: Shows supported features of the API
  - name: matter
    description: Contains information about the type of legal work
  - name: document
    description: Contains information about legal documents

paths:
  /supported/tags:
    get:
      tags:
        - supported
      summary: Show all the SALI LMSS fields/tags supported by the implementer of the API
      description: |
        Show all the SALI LMSS fields/tags supported by the implementer of the API. Includes a list of custom fields.<br>
        - Implementers of the SALI API standard support the LMSS hierarchy/ontology, including parent-child relationships (ancestors and descendants).
        - When SALI API User performs an API Call, finding information, the API Response results will include all of a tag’s descendents (e.g., children, grandchildren).
        - API Responses will show the hierarchy’s last child node (the lowest descendant “leaf”). For example, for a matter involving <i>"Area of Law" > "Corporate Law" > "Business Organizations Law"</i>, the API Response results will show the lowest descendant leaf: <i>"Business Organizations Law"</i> <http://lmss.sali.org/R8AC0Iq3zua7VGgBd0jCBtz>.
        - API Responses will not (currently) show a Parent-Child Relationships. Instead, the API Caller would do the necessary LMSS relationship mapping on the API Caller’s Production side (not the API side).
        - This endpoint contains all fields/tags supported by the API Implementer, irrespective of parent-child relationship. Example: <i>"rdfs:label":Area of Law", "rdfs:label":"Corporate Law", "rdfs:label":"Business Organizations Law"</i>.""
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  saliVersion:
                    type: integer
                    format: int64
                    example: 1.0.0
                  saliTags:
                    type: array
                    items:
                      type: object
                      properties:
                        sali:IRI:
                          type: string
                          format: string
                        rdfs:label:
                          type: string
                          format: string
                        supportedOperation:
                          type: string
                          format: string
                      example:
                        - sali:IRI: http://lmss.sali.org/R3391bdB1A2adE51071C7cf7
                          rdfs:label: "New York State Courts"
                          supportedOperation: "/matter/find:request, /matter/find:response, /document/find:request, /document/find:response"
                        - sali:IRI: http://lmss.sali.org/RSYBzf149Mi5KE0YtmpUmr
                          rdfs:label: "Area of Law"
                          supportedOperation: "/matter/find:request, /matter/find:response"
                  customTags:
                    type: array
                    items:
                      type: object
                      properties:
                        custom:label:
                          type: string
                          format: string
                        type:
                          type: string
                          format: string
                        supportedOperation:
                          type: string
                          format: string
                      example:
                        - custom:label: "vLex-system-location"
                          type: "string"
                          supportedOperation: "/matter/find:request, /matter/find:response"
        "404":
          description: Not found

  /matter/find:
    post:
      tags:
        - matter
      summary: Find a list of matters based on standard LMSS fields/tags
      description: Find a list of matters based on standard LMSS fields/tags, including supported custom fields. The request query follows Resource Query Language (RQL) structure.
      requestBody:
        description: The query to find matters information from LMSS tags
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 57
                  matters:
                    type: array
                    items:
                      $ref: "#/components/schemas/Matter"
        "405":
          description: Invalid input
  /document/find:
    post:
      tags:
        - document
      summary: Find a list of documents based on standard LMSS fields/tags
      description: Find a list of documents based on standard LMSS fields/tags including supported custom fields. The request query follows Resource Query Language (RQL) structure.
      operationId: findDocs
      requestBody:
        description: The query to find documents information from LMSS tags
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 57
                  documents:
                    type: array
                    items:
                      $ref: "#/components/schemas/Document"
        "405":
          description: Invalid input
components:
  schemas:
    Query:
      type: object
      properties:
        operatorName: 
          type: string
          example: "sali:and"
        args: 
          type: array
          items: 
            type: object
            properties: 
              operatorName: 
                type: string
              args:
                type: array
                items:
                  type: object
                  properties:
                    sali:IRI:
                      type: string
                    rdfs:label:
                      type: string
                    custom:label:
                      type: string
                    filter:
                      type: string
                    operatorName:
                      type: string
              sali:IRI:
                type: string
              rdfs:label:
                type: string
              custom:label:
                type: string
              filter:
                type: string
          example:
            - operatorName: "sali:or"
              args:
                - operatorName: "sali:contains"
                  sali:IRI: "http://lmss.sali.org/R9pmjLDKAMzm147xIPPq5ul"
                  rdfs:label: "Energy Law"
                - operatorName: "sali:contains"
                  sali:IRI: "http://lmss.sali.org/RYdDlq7cXsPj2kB0yDsDGF"
                  rdfs:label: "Agriculture Law"
                - operatorName: "sali:contains"
                  sali:IRI: "http://lmss.sali.org/R76LI21wQ90B6IH1x5jfFy0"
                  rdfs:label: "Litigation Docket Number"
                  filter: "4:22-cv-06823"
            - operatorName: "sali:contains"
              sali:IRI: "http://lmss.sali.org/R3391bdB1A2adE51071C7cf7"
              rdfs:label: "New York State Courts"
            - operatorName: "sali:contains"
              custom:label: "vLex-system-location"
              filter: "Minneapolis-St. Paul"
    Matter:
      type: object
      properties:
        systemId:
          type: string
          format: string
          example: 31dd6174-a68b-4cb4-985a-0e8b605bc90b
        title:
          type: string
          example: "Wage and hour class action against Acme Corp"
        data:
          type: array
          items:
            type: object
            properties:
              sali:IRI:
                type: string
              rdfs:label:
                type: string
              value:
                type: string
            example:
              - sali:IRI: http://lmss.sali.org/RhyNTbD8DpP50zo0gCEt8g
                rdfs:label: "Client Name"
                value: "Acme Corp"
              - sali:IRI: http://lmss.sali.org/R3391bdB1A2adE51071C7cf7
                rdfs:label: "New York State Courts"
              - sali:IRI: http://lmss.sali.org/R88iESKPlMDuSSfwDVX9scA
                rdfs:label: "Wage and Hour Law"
              - sali:IRI: http://lmss.sali.org/RBMvEUoQqGGasSOnlMKAkpp
                rdfs:label: "Currency"
                value: "USD"
              - sali:IRI: http://lmss.sali.org/RDfdmGR6iPi4k2t6ecIUBkP
                rdfs:label: "Retail Trade Industry"
    Document:
      type: object
      properties:
        systemId:
          type: string
          format: string
          example: 31dd6174-a68b-4cb4-985a-0e8b605bc90b
        title:
          type: string
          example: "Employment contract for Jane Doe"
        data:
          type: array
          items:
            type: object
            properties:
              sali:IRI:
                type: string
              rdfs:label:
                type: string
              value:
                type: string
            example:
              - sali:IRI: http://lmss.sali.org/RhyNTbD8DpP50zo0gCEt8g
                rdfs:label: "Client Name"
                value: "Acme Corp"
              - sali:IRI: http://lmss.sali.org/R3391bdB1A2adE51071C7cf7
                rdfs:label: "New York State Courts"
              - sali:IRI: http://lmss.sali.org/R88iESKPlMDuSSfwDVX9scA
                rdfs:label: "Wage and Hour Law"
              - sali:IRI: http://lmss.sali.org/RBMvEUoQqGGasSOnlMKAkpp
                rdfs:label: "Currency"
                value: "USD"
              - sali:IRI: http://lmss.sali.org/RDfdmGR6iPi4k2t6ecIUBkP
                rdfs:label: "Retail Trade Industry"