openapi: 3.0.3
info:
  title: SALI DRAFT API Standards v0.2
  description: |-
    SALI is a nonprofit organization comprised of legal industry professionals from corporate law departments, law firms, and solution providers with the goal of developing open, practical industry standards for efficient and innovative legal services. More information at: [https://www.sali.org](https://www.sali.org)._

    This document contains a set of API Standrads compliant with SALI and the [Legal Matter Specification Standard](https://www.sali.org/Using-the-LMSS).

  license:
    name: SALI Open Standard Policy
    url: https://github.com/sali-legal/api/blob/main/LICENSE
  version: 1.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/SALI-LMSS-V1/LMSS-API/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://app.swaggerhub.com/apis/SALI-LMSS-V1/LMSS-API/1.0.0
tags:
  - name: supported
    description: Shows the API's supported features
  - name: matter
    description: Contains information about the legal work
  - name: document
    description: Contains information about legal documents

paths:
  /supported/fields:
    get:
      tags:
        - supported
      summary: Show all the SALI LMSS fields/tags supported by the API implementer
      description: Show all the SALI LMSS fields/tags supported by the API implementer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  saliVersion:
                    type: integer
                    format: int64
                    example: 1.0.0
                  fields:
                    type: array
                    items:
                      type: object
                      properties:
                        sali:IRI:
                          type: string
                          format: string
                        rdfs:label:
                          type: string
                          format: string
                      example:
                        - sali:IRI: http://lmss.sali.org/R3391bdB1A2adE51071C7cf7
                          rdfs:label: "New York State Courts"
                        - sali:IRI: http://lmss.sali.org/RSYBzf149Mi5KE0YtmpUmr
                          rdfs:label: "Area of Law"
        "404":
          description: Not found

  /matter/find:
    post:
      tags:
        - matter
      summary: Using standard LMSS fields, find a list of matters 
      description: Using standard LMSS fields, find a list of matters 
      requestBody:
        description: The query to find matters information from LMSS tags
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  sali:IRI:
                    type: string
                  rdfs:label:
                    type: string
                  filter:
                    type: string
                  operation:
                    type: string
                example:
                  - sali:IRI: "http://lmss.sali.org/R3391bdB1A2adE51071C7cf7"
                    rdfs:label: "New York State Courts"
                    filter:
                    operation:
                  - sali:IRI: "http://lmss.sali.org/RSYBzf149Mi5KE0YtmpUmr"
                    rdfs:label: "Area of Law"
                    filter: "Tax"
                    operation: "CONTAINS"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 57
                  matters:
                    type: array
                    items:
                      $ref: "#/components/schemas/Matter"
        "405":
          description: Invalid input
  /document/find:
    post:
      tags:
        - document
      summary: Using standard LMSS tags, find a list of documents.
      description: Using standard LMSS tags, find a list of documents.
      operationId: findDocs
      requestBody:
        description: The query to use LMSS tags to find document information
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  sali:IRI:
                    type: string
                  rdfs:label:
                    type: string
                  filter:
                    type: string
                  operation:
                    type: string
                example:
                  - sali:IRI: "http://lmss.sali.org/R3391bdB1A2adE51071C7cf7"
                    rdfs:label: "New York State Courts"
                    filter:
                    operation:
                  - sali:IRI: "http://lmss.sali.org/RSYBzf149Mi5KE0YtmpUmr"
                    rdfs:label: "Area of Law"
                    filter: "Tax"
                    operation: "eq"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 57
                  matters:
                    type: array
                    items:
                      $ref: "#/components/schemas/Document"
        "405":
          description: Invalid input

# QUESTION: The below appear to be from LMSS 1.0, but I'm not sure whether they continue to be valid with LMSS 2.0
# ANSWER: Damien will add
# QUESTION: Is the language "Wage and hour class action against XYZ Corp" a natural language query? Or a value (from a database)?
# ANSWER: This is an organization-defined value/field. The "Wage and Hour..." language is a `Matter Narrative Description`

# Same question: "Jane Smith and co-workers" = natural language query (e.g., LLM query)
# ANSWER: Same as above

# Also, is everything below conjunct (AND) or disjunct (OR)?
# ANSWER: Default = And
# Regardless, will we handle those AND/OR/NOT operators?

# Also, how will we run a query for a specific string (e.g., `4:22-cv-06823` = `Litigation Docket Number` http://lmss.sali.org/R76LI21wQ90B6IH1x5jfFy0)?
# In this documentation, can we give multiple examples?

components:
  schemas:
    supportedField:
      type: object
      properties:
        saliVersion:
          type: integer
          format: int64
          example: 1.0.0
        fields:
          type: array
          items:
            type: object
            properties:
              sali:IRI:
                type: string
                format: string
              rdfs:label:
                type: string
                format: string
            example:
              - sali:IRI: http://lmss.sali.org/R3391bdB1A2adE51071C7cf7
                rdfs:label: "New York State Courts"
              - sali:IRI: http://lmss.sali.org/RSYBzf149Mi5KE0YtmpUmr
                rdfs:label: "Area of Law"
    Matter:
      type: object
      properties:
        lmssId:
          type: string
          format: string
          example: A-B-C-D
        title:
          type: string
          example: "Wage and Hour Law." sali:IRI: http://lmss.sali.org/R88iESKPlMDuSSfwDVX9scA
          
        locale:
          type: string
          example: "NAM-US-US+NY"
        process:
          $ref: "#/components/schemas/Process"
    Process:
      type: object
      properties:
        processType:
          type: string
          Civil Dispute
          example: "http://lmss.sali.org/R79LjWBKHCdmQKEW6zPY8Co"
        areaOfLaw:
          type: string
          example: "LEMP-WGHR"
        actor:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: Jane Smith and co-workers
              role:
                type: string
                example: PLTF
              legalEntity:
                type: string
              claim:
                type: string
                example: Breach of Contract
                sali:IRI: http://lmss.sali.org/RC2fjcpsEbrVvVymvt4oASx
    Document:
      type: object
      properties:
        lmssId:
          type: string
          format: string
          example: A-B-C-D
        title:
          type: string
          example: "Wage and hour class action against XYZ Corp."
